name: ci
on:
  push
jobs:
  run-python-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: python
    strategy:
      matrix:
        version: ['3.9', '3.10']
        params:
          - {test_group_indices: "0,1"}
          - {test_group_indices: "2,3"}
    env:
      NUM_PARALLELIZATION: 4  # 2 jobs x 2 processes
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: Run tests
        env:
          TEST_GROUP_INDICES: ${{ matrix.params.test_group_indices }}
        run: |
          python parallel_test_run.py
  run-php-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: php
    strategy:
      matrix:
        version: ['8.0', '8.1']
        params:
          - {test_group_indices: "0,1"}
          - {test_group_indices: "2,3"}
    env:
      NUM_PARALLELIZATION: 4  # 2 jobs x 2 processes
    steps:
      - uses: actions/checkout@v2
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ matrix.version }}-${{ hashFiles('**/composer.lock') }}
      - name: Install dependencies
        run: |
          composer install
      - name: Run tests
        env:
          TEST_GROUP_INDICES: ${{ matrix.params.test_group_indices }}
        run: |
          ./vendor/bin/phpunit --do-not-cache-result
