name: ci
on:
  push
jobs:
  run-python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        params:
          - {test_group_indices: "0,1"}
          - {test_group_indices: "2,3"}
    env:
      NUM_PARALLELIZATION: 4  # 2 jobs x 2 processes
    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.9'
      - name: Run tests
        env:
          TEST_GROUP_INDICES: ${{ matrix.params.test_group_indices }}
        run: |
          python parallel_test_run.py
  run-php-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: php-test-parallelization
    strategy:
      matrix:
        params:
          - {test_group_indices: "0,1"}
          - {test_group_indices: "2,3"}
    env:
      NUM_PARALLELIZATION: 4  # 2 jobs x 2 processes
    steps:
      - uses: actions/checkout@v2
      - name: Setup php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
      - name: Install dependencies
        run: |
          ./composer.phar install
      - name: Run tests
        env:
          TEST_GROUP_INDICES: ${{ matrix.params.test_group_indices }}
        run: |
          ./vendor/bin/phpunit --do-not-cache-result
